### ISSUE TITLE
Incompatible with Browser gem v2

### ISSUE THREAD

**Issue by losadaem** [assembler/browsernizer#17]
The class constructor has a different signature now. It has changed from
```
Browser.new(
  ua: request.headers["User-Agent"],
  accept_language: request.headers["Accept-Language"]
)
```
to
```
Browser.new(
  request.headers["User-Agent"],
  accept_language: request.headers["Accept-Language"]
)
```

Some methods has changed too. For example `browser.mobile?` is now `browser.device.mobile?`

**Comment by assembler** [comment]
handled with https://github.com/assembler/browsernizer/pull/18
